### ISSUE TITLE
No manual install possible

### ISSUE THREAD

**Issue by francwalter** [cliffparnitzky/TinyMceBundleClassic#1]
There is no way to install this extension manually.
The zip contains only the composer.json.

**Comment by cliffparnitzky** [comment]
Yep, thats right, this is only a composer package (have a look at the readme / description) to bundle all dependencies ...

**Comment by francwalter** [comment]
Did I wrong understand that the composer is not yet the stable extension/package manager?
I have a productive website so I don't want to install betas.

**Comment by cliffparnitzky** [comment]
Installing the bundle without a composer client is very hard. You have to follow the dependencies in the composer.json, get all depending packages and install them manually.

Or use a test installation, install via composer client and copy all folders and files. 

Since Contao 3.3  am using the composer client in each installation, stable and without problemes.

**Comment by francwalter** [comment]
OK thank, I will install composer then on a test environment and use it there firstly for a while.

**Comment by cliffparnitzky** [comment]
:+1:
